// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1UAQ0d5AjrJZvoljpXbT7QrUI9wr_eRI',
    appId: '1:224927663250:web:200480b22e803c63a4524b',
    messagingSenderId: '224927663250',
    projectId: 'eco-memories',
    authDomain: 'eco-memories.firebaseapp.com',
    databaseURL: 'https://eco-memories-default-rtdb.firebaseio.com',
    storageBucket: 'eco-memories.appspot.com',
    measurementId: 'G-YWBR992K05',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1UAQ0d5AjrJZvoljpXbT7QrUI9wr_eRI',
    appId: '1:224927663250:web:200480b22e803c63a4524b',
    messagingSenderId: '224927663250',
    projectId: 'eco-memories',
    authDomain: 'eco-memories.firebaseapp.com',
    databaseURL: 'https://eco-memories-default-rtdb.firebaseio.com',
    storageBucket: 'eco-memories.appspot.com',
    measurementId: 'G-YWBR992K05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtDb-ReOmKxYguhhuv3F1hszyym4KB2g0',
    appId: '1:224927663250:ios:c8a31caa53de09a6a4524b',
    messagingSenderId: '224927663250',
    projectId: 'eco-memories',
    databaseURL: 'https://eco-memories-default-rtdb.firebaseio.com',
    storageBucket: 'eco-memories.appspot.com',
    iosClientId:
        '224927663250-2i5kvbtlemn3ovi740v25qlarj14f0fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoMemories',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDb-ReOmKxYguhhuv3F1hszyym4KB2g0',
    appId: '1:224927663250:ios:c8a31caa53de09a6a4524b',
    messagingSenderId: '224927663250',
    projectId: 'eco-memories',
    databaseURL: 'https://eco-memories-default-rtdb.firebaseio.com',
    storageBucket: 'eco-memories.appspot.com',
    iosClientId:
        '224927663250-2i5kvbtlemn3ovi740v25qlarj14f0fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoMemories',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5OAXO0LL1uh_e7u1rza-s7jVajPWeK8',
    appId: '1:224927663250:android:6eb63a83917b4c78a4524b',
    messagingSenderId: '224927663250',
    projectId: 'eco-memories',
    databaseURL: 'https://eco-memories-default-rtdb.firebaseio.com',
    storageBucket: 'eco-memories.appspot.com',
  );
}
